languages:
  PHP: true

exclude_paths:
  - mime.types.php
  - build/**/*
  - tests/**/*
  - vendor/**/*

engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
